displayName=Rune Shop Value
author=20pc-Nugget
description=Displays the value of runes in your inventory and rune pouch if sold to Ali Morrisane's store.
tags=ali,morrisane,runes,runecraft,calculator,value,uim,ironman
plugins=com.runeshopvalue.RuneShopValuePlugin
build=standard
