displayName=Rune Shop Value
author=20pc-Nugget
description=Shows the sell value of your runes at Ali Morrisane's shop
tags=shop, value, ali morrisane, runes, buy, sell, profit, calculator
plugins=com.runeshopvalue.RuneShopValuePlugin
build=standard
